name: build

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    env:
        DOTNET_NOLOGO: true
        DOTNET_CLI_TELEMETRY_OPTOUT: true
    runs-on: windows-latest
    if: always()

    steps:
        - uses: actions/checkout@v3

        - name: Setup .NET Core SDK
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: 6

        - name: Output dotnet info
          run: dotnet --info

        - name: Unit tests
          run: |
            dotnet restore
            dotnet test -p:CollectCoverage=true -p:CoverletOutputFormat=opencover -p:Threshold=0
        - name: Upload to codecov
          uses: codecov/codecov-action@v1

  notify_success:
    runs-on: ubuntu-latest
    needs: [build]
    if: success()
    steps:
      - env:
          TEAMS_WEBHOOK_URL: ${{secrets.TEAMS_WEBHOOK_URL}}
        run: |
            cat << EOF > message.json
            {"@type":"MessageCard","@context":"https://schema.org/extensions","summary":"Pipeline Success","themeColor":"22c55e","title":"✅ $GITHUB_REPOSITORY pipeline was successful!","sections":[{"facts":[{"name":"Repository:","value":"$GITHUB_REPOSITORY"},{"name":"Branch:","value":"$GITHUB_REF_NAME"},{"name":"Commit:","value":"$GITHUB_SHA"}]}],"potentialAction":[{"@type":"OpenUri","name":"View on GitHub","targets":[{"os":"default","uri":"$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"}]}]}
            EOF
            curl -X POST $TEAMS_WEBHOOK_URL --header 'Content-Type: application/json' -d @message.json

  notify_failure:
    runs-on: ubuntu-latest
    needs: [build]
    if: failure()
    steps:
      - env:
          TEAMS_WEBHOOK_URL: ${{secrets.TEAMS_WEBHOOK_URL}}
        run: |
          cat << EOF > message.json
          {"@type":"MessageCard","@context":"https://schema.org/extensions","summary":"Pipeline Failed","themeColor":"ef4444","title":"⛔ $GITHUB_REPOSITORY pipeline failed!","sections":[{"facts":[{"name":"Repository:","value":"$GITHUB_REPOSITORY"},{"name":"Branch:","value":"$GITHUB_REF_NAME"},{"name":"Commit:","value":"$GITHUB_SHA"}]}],"potentialAction":[{"@type":"OpenUri","name":"View on GitHub","targets":[{"os":"default","uri":"$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"}]}]}
          EOF
          curl -X POST $TEAMS_WEBHOOK_URL --header 'Content-Type: application/json' -d @message.json
