name: build

on:
    push:
        branches: ["*"]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        env:
            DOTNET_NOLOGO: true
            DOTNET_CLI_TELEMETRY_OPTOUT: true
        runs-on: windows-latest
        if: always()

        steps:
            - uses: actions/checkout@v2

            - name: Setup .NET Core SDK
              uses: actions/setup-dotnet@v1.7.2
              with:
                  dotnet-version: 6

            - name: Output dotnet info
              run: dotnet --info

            - name: Unit tests
              run: |
                  dotnet restore
                  dotnet test -p:CollectCoverage=true -p:CoverletOutputFormat=opencover -p:Threshold=0

            - name: Upload to codecov
              uses: codecov/codecov-action@v1

    notify_success:
        runs-on: ubuntu-latest
        needs: [build]
        if: success()
        steps:
            - uses: neonidian/teams-notify-build-status@v3
              with:
                  titleBackgroundColor: ${{ job.status }}
                  webhookUrl: ${{ secrets.TEAMS_WEBHOOK_URL }}
                  title: >-
                      [Repository link](${{ github.server_url }}/${{ github.repository }})
                  message: Successful build
              env:
                  SHOULD_DISPLAY_VIEW_RUN_BUTTON: true

    notify_failure:
        runs-on: ubuntu-latest
        needs: [build]
        if: failure()
        steps:
            - uses: neonidian/teams-notify-build-status@v3
              with:
                  titleBackgroundColor: ${{ job.status }}
                  webhookUrl: ${{ secrets.TEAMS_WEBHOOK_URL }}
                  title: >-
                      [Repository link](${{ github.server_url }}/${{ github.repository }})
                  message: Build failed
                  status: Failure
              env:
                  SHOULD_DISPLAY_VIEW_RUN_BUTTON: true
                  SHOULD_DISPLAY_VIEW_COMMIT_BUTTON: true
                  SHOULD_DISPLAY_ACTOR_LABEL: true
