name: build

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    env:
        DOTNET_NOLOGO: true
        DOTNET_CLI_TELEMETRY_OPTOUT: true
    runs-on: windows-latest
    if: always()

    steps:
        - uses: actions/checkout@v3

        - name: Setup .NET Core SDK
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: 6

        - name: Install Node.js
          uses: actions/setup-node@v3
          with:
            node-version: 16.14.2

        - uses: pnpm/action-setup@v2
          name: Install pnpm
          id: pnpm-install
          with:
            version: 8.1.0
            run_install: false

        - name: Output dotnet info
          run: dotnet --info

        - name: Install dependencies
          run: pnpm install

        - name: Unit tests
          run: |
            dotnet restore
            dotnet test -p:CollectCoverage=true -p:CoverletOutputFormat=opencover -p:Threshold=0
        - name: Upload to codecov
          uses: codecov/codecov-action@v1
